[ExtraButton]
Meter=Button
ButtonImage=#@#Images\zpecial.png
X=#XTRA#
Y=#YSTART#
ButtonCommand=[!ToggleConfig "MiniMal\Settings" "Settings.ini"]

[ButtonA]
Meter=Shape
Shape=Rectangle #XA#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonAStr]
Meter=String
Text=A
X=#XA# + 25 - ([ButtonAStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonAStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonB]
Meter=Shape
Shape=Rectangle #XB#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonBStr]
Meter=String
Text=B
X=#XB# + 25 - ([ButtonBStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonBStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonC]
Meter=Shape
Shape=Rectangle #XC#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonCStr]
Meter=String
Text=C
X=#XC# + 25 - ([ButtonCStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonCStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonD]
Meter=Shape
Shape=Rectangle #XD#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonDStr]
Meter=String
Text=D
X=#XD# + 25 - ([ButtonDStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonDStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonE]
Meter=Shape
Shape=Rectangle #XE#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonEStr]
Meter=String
Text=E
X=#XE# + 25 - ([ButtonEStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonEStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonF]
Meter=Shape
Shape=Rectangle #XF#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonFStr]
Meter=String
Text=F
X=#XF# + 25 - ([ButtonFStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonFStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonG]
Meter=Shape
Shape=Rectangle #XG#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonGStr]
Meter=String
Text=G
X=#XG# + 25 - ([ButtonGStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonGStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonH]
Meter=Shape
Shape=Rectangle #XH#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonHStr]
Meter=String
Text=H
X=#XH# + 25 - ([ButtonHStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonHStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonI]
Meter=Shape
Shape=Rectangle #XI#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonIStr]
Meter=String
Text=I
X=#XI# + 25 - ([ButtonIStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonIStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonJ]
Meter=Shape
Shape=Rectangle #XJ#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonJStr]
Meter=String
Text=J
X=#XJ# + 25 - ([ButtonJStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonJStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonK]
Meter=Shape
Shape=Rectangle #XK#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonKStr]
Meter=String
Text=K
X=#XK# + 25 - ([ButtonKStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonKStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonL]
Meter=Shape
Shape=Rectangle #XL#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonLStr]
Meter=String
Text=L
X=#XL# + 25 - ([ButtonLStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonLStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonM]
Meter=Shape
Shape=Rectangle #XM#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonMStr]
Meter=String
Text=M
X=#XM# + 25 - ([ButtonMStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonMStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonN]
Meter=Shape
Shape=Rectangle #XN#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonNStr]
Meter=String
Text=N
X=#XN# + 25 - ([ButtonNStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonNStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonO]
Meter=Shape
Shape=Rectangle #XO#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonOStr]
Meter=String
Text=O
X=#XO# + 25 - ([ButtonOStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonOStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonP]
Meter=Shape
Shape=Rectangle #XP#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonPStr]
Meter=String
Text=P
X=#XP# + 25 - ([ButtonPStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonPStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonQ]
Meter=Shape
Shape=Rectangle #XQ#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonQStr]
Meter=String
Text=Q
X=#XQ# + 25 - ([ButtonQStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonQStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonR]
Meter=Shape
Shape=Rectangle #XR#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonRStr]
Meter=String
Text=R
X=#XR# + 25 - ([ButtonRStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonRStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonS]
Meter=Shape
Shape=Rectangle #XS#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonSStr]
Meter=String
Text=S
X=#XS# + 25 - ([ButtonSStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonSStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonT]
Meter=Shape
Shape=Rectangle #XT#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonTStr]
Meter=String
Text=T
X=#XT# + 25 - ([ButtonTStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonTStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonU]
Meter=Shape
Shape=Rectangle #XU#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonUStr]
Meter=String
Text=U
X=#XU# + 25 - ([ButtonUStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonUStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonV]
Meter=Shape
Shape=Rectangle #XV#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonVStr]
Meter=String
Text=V
X=#XV# + 25 - ([ButtonVStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonVStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonW]
Meter=Shape
Shape=Rectangle #XW#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonWStr]
Meter=String
Text=W
X=#XW# + 25 - ([ButtonWStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonWStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonX]
Meter=Shape
Shape=Rectangle #XX#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonXStr]
Meter=String
Text=X
X=#XX# + 25 - ([ButtonXStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonXStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonY]
Meter=Shape
Shape=Rectangle #XY#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonYStr]
Meter=String
Text=Y
X=#XY# + 25 - ([ButtonYStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonYStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1

[ButtonZ]
Meter=Shape
Shape=Rectangle #XZ#,(#YSTART#),50,50 | StrokeWidth 0 | Fill Color #MainColor#
LeftMouseUpAction=

[ButtonZStr]
Meter=String
Text=Z
X=#XZ# + 25 - ([ButtonZStr:W] / 2)
Y=#YSTART# + 25 - ([ButtonZStr:H] / 2)
FontColor=#SecondaryColor#
FontSize=(#FontSize# + 11)
FontFace=#FontFace#
DynamicVariables=1
